/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List News
         * @description Visible items by default (`visibility`); `q` searches title and text, `since` bounds the period.
         */
        get: operations["list_news__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news__news_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{news_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss News
         * @description Hide the item from the feed (`dismissed_at`); a repeat keeps the first moment.
         */
        post: operations["dismiss_news__news_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{news_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore News
         * @description Bring a hidden item back into the feed.
         */
        post: operations["restore_news__news_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{news_id}/npa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Escalate News
         * @description Flag the item as an alert and register it as an act in npa_service — atomically:
         *     if npa_service does not confirm, the flag is rolled back. Without a body the act is
         *     built from the news item itself.
         */
        post: operations["escalate_news__news_id__npa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewsOut */
        NewsOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Link */
            source_link: string;
            /** Source Name */
            source_name: string;
            source_type: components["schemas"]["SourceType"];
            source_reliability: components["schemas"]["SourceReliability"];
            /** Source Tags */
            source_tags: string[];
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Excerpt */
            excerpt: string | null;
            /** Published At */
            published_at: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Dismissed At */
            dismissed_at: string | null;
            /** Is Alert */
            is_alert: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NewsPage */
        NewsPage: {
            /** Items */
            items: components["schemas"]["NewsOut"][];
            /** Total */
            total: number;
        };
        /**
         * NewsVisibility
         * @description Which items the feed shows: the ones a reader has not hidden, only the hidden, or both.
         * @enum {string}
         */
        NewsVisibility: "visible" | "dismissed" | "all";
        /**
         * NpaDTO
         * @description A legislative act to register. `url` identifies it (unique in the store).
         */
        NpaDTO: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Title */
            title: string;
            /**
             * Text
             * @default
             */
            text?: string;
            /** Published At */
            published_at?: string | null;
        };
        /**
         * SourceReliability
         * @description How trustworthy a source's reporting is, curated per source.
         * @enum {string}
         */
        SourceReliability: "high" | "medium" | "low";
        /**
         * SourceType
         * @description How a source is collected.
         * @enum {string}
         */
        SourceType: "telegram" | "rss" | "web";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_news__get: {
        parameters: {
            query?: {
                q?: string | null;
                since?: string | null;
                visibility?: components["schemas"]["NewsVisibility"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news__news_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_news__news_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_news__news_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_news__news_id__npa_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NpaDTO"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
