"""Persistence contract for summarized-news ingestion and event clustering."""

from typing import Protocol

from news_service.domain.event_cluster import CandidateCluster, CandidateQuery, ClusterAssignment
from news_service.domain.event_summary import EventSummary, PreparedNews, StoredNewsState


class DedupRepository(Protocol):
    async def list_states(self, urls: list[str]) -> dict[str, StoredNewsState]: ...

    async def save_summaries(self, items: list[PreparedNews]) -> None: ...

    async def list_unembedded(self, urls: list[str]) -> list[EventSummary]: ...

    async def save_embeddings(self, summaries: list[EventSummary]) -> None: ...

    async def list_pending(self, urls: list[str]) -> list[EventSummary]: ...

    async def find_candidates(self, query: CandidateQuery) -> list[CandidateCluster]: ...

    async def assign_clusters(self, assignments: list[ClusterAssignment]) -> None: ...
